#!/bin/sh
### BEGIN INIT INFO
# Provides:          iptotal
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: monitor for IP traffic, not requiring SNMP
# Description: This scripts start, restart and stop iptotal traffic
#              monitoring tool. 
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/iptotald
NAME=iptotal
DESC="IP traffic monitor"
PIDFILE=/var/run/$NAME.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

# Include iptotal defaults if available
if [ -f /etc/default/iptotal ] ; then
	. /etc/default/iptotal
fi

set -e

case "$1" in
  start)
    if [ "$ENABLE_DAEMON" != "yes" ] && [ "$ENABLE_DAEMON" != "YES" ]; then
        echo "Not starting iptotald. Disabled via /etc/default/iptotal"
        exit 0
    fi
	echo -n "Starting $DESC: "
	start-stop-daemon -b --start --quiet --pidfile $PIDFILE \
		--exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --oknodo --stop --quiet --pidfile $PIDFILE 
    rm -f $PIDFILE
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet --pidfile $PIDFILE
    rm -f $PIDFILE
	sleep 1
	start-stop-daemon -b --start --quiet --pidfile \
		$PIDFILE --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  force-start)
    echo -n "Starting $DESC: "
    start-stop-daemon -b --start --quiet --pidfile $PIDFILE \
        --exec $DAEMON -- $DAEMON_OPTS
    echo "$NAME."
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload|force-start}" >&2
	exit 1
	;;
esac
