#!/bin/sh
#
# Author: Dario Minnucci <debian@midworld.net>
# Date:   Tue, 25 Aug 2009 02:52:05 +0200
# Updated by: Ignace Mouzannar <mouzannar@gmail.com>
#

set -e

case "$1" in
	configure)
	    chown -R www-data:www-data /usr/lib/iptotal/*

	    # reload apache2 configuration
	    invoke-rc.d apache2 reload

        # Copy old user files (if they are present)
        if [ -d "/var/www/iptotal/archive" ]; then
            cp /var/www/iptotal/archive/* /usr/lib/iptotal/archive/
        fi
        for file in iptotal.rrd result.txt
        do
            if [ -f "/var/www/iptotal/${file}" ]; then
                cp /var/www/iptotal/${file} /usr/lib/iptotal/
            fi
        done
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*) 
	    echo "postinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac

#DEBHELPER#

exit 0
